spring.application.name=internship_tracking_and_evaluation
spring.datasource.url=jdbc:mysql://localhost:3306/internship_tracking_evaluation
spring.datasource.username=root
spring.datasource.password=sunshine9600
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.port=8080
